[#2] Mocks de notícias criados, listagem criada e layout testado
vitrentin/intoxianime pull request #4
Opened 2023-09-14 21:32 UTC by vitrentin

Resolved

2023-09-15 10:23 UTC, rod-moraes requested changes
Opa Trentin, espero que esteja tudo bem com você, segue as alterações requeridas, e perguntas sobre a regra, obrigado!!!!

2023-09-15 10:23 UTC, rod-moraes commented on lib/app/modules/home/data/adapters/news_adapter.dart
> +      aboutAnime: e['yoast_head'],
E se esses campos forem nulos? Vai dar erro, eles realmente são requeridos? Favor só validar isso para mim e responder aqui!!!!

2023-09-15 10:23 UTC, rod-moraes commented on lib/app/modules/home/data/model/news_model.dart
> +  final String aboutAnime;
São somente esses campos???? Sera que não existe outros campos que devam ser usados???? todos são obrigatórios??? favor responder aqui!!!

2023-09-15 10:23 UTC, rod-moraes commented on lib/app/modules/home/data/service/news_services.dart
> +      'https://www.intoxianime.com/?rest_route=/wp/v2/posts&page=1&per_page=10',
Criar uma variavel PATH com o inicio da rota, e colocar ele como baseURL, para não ficar dessa forma, além disso, utilizar o queryParams do DIO para passar os parametros!!!!

2023-09-15 10:23 UTC, rod-moraes commented on lib/app/modules/home/presenter/pages/home_page.dart
> +              ),
Criar um componente separado para esse widget, pois ele é um componente só para estilização e não precisa necessariamente ficar aqui tomando tanto espaço de tela no código

2023-09-15 10:23 UTC, rod-moraes commented on lib/app/modules/home/presenter/pages/home_page.dart
> +        ),
Criar um componente chamado "BackgroundWithCircleBlur" e passar toda essa lógica para esse componente em um arquivo separado, lembrar de pegar o CircleBlur e colocar nesse arquivo também

2023-09-15 10:23 UTC, rod-moraes commented on lib/app/modules/home/presenter/pages/home_page.dart
>  }
Esse é o CircleBlur, colocar ele junto com o widget de background

2023-09-15 10:23 UTC, rod-moraes commented on lib/app/modules/home/presenter/widgets/card_new_widget.dart
> +// ignore_for_file: lines_longer_than_80_chars
Uai

2023-09-15 10:23 UTC, rod-moraes commented on lib/app/modules/home/presenter/widgets/card_new_widget.dart
> +                'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque lorem ipsun dolor, lorem ipsum doooolor aaa',
Quebrar em menos linhas, o lint está reclamando!!!

2023-09-15 10:31 UTC, vitrentin commented on lib/app/modules/home/data/adapters/news_adapter.dart
> +      aboutAnime: e['yoast_head'],
Esses campos não são nulos de acordo com a database, porém caso forem, retornarão 0, ou ' '

2023-09-15 10:34 UTC, vitrentin commented on lib/app/modules/home/data/model/news_model.dart
> +  final String aboutAnime;
Serão somente esses campos que serão utilizados, todos são obrigatórios para compor a notícia.

2023-09-15 10:40 UTC, vitrentin commented on lib/app/modules/home/presenter/pages/home_page.dart
> +              ),
Resolvido

2023-09-15 10:54 UTC, vitrentin commented on lib/app/modules/home/data/service/news_services.dart
> +      'https://www.intoxianime.com/?rest_route=/wp/v2/posts&page=1&per_page=10',
Resolvido

2023-09-15 11:00 UTC, vitrentin commented on lib/app/modules/home/presenter/pages/home_page.dart
> +        ),
Resolvido

2023-09-15 11:00 UTC, vitrentin commented on lib/app/modules/home/presenter/pages/home_page.dart
>  }
Feito

2023-09-15 11:04 UTC, vitrentin commented on lib/app/modules/home/presenter/widgets/card_new_widget.dart
> +// ignore_for_file: lines_longer_than_80_chars
Coloquei a descrição da notícia como String multilinha para não precisar ignorar esse aviso

2023-09-15 11:04 UTC, vitrentin commented on lib/app/modules/home/presenter/widgets/card_new_widget.dart
> +                'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque lorem ipsun dolor, lorem ipsum doooolor aaa',
Resolvido

2023-09-17 12:11 UTC, rod-moraes approved these changes

2023-09-19 10:33 UTC, merged